version: 2

build:
  image: latest

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

# Install regular dependencies.
# Then, install special pinning for RTD.
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - graphviz
  jobs:
    post_checkout:
      - git fetch --unshallow || true

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - all

# Don't build any extra formats
formats: []
